// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ColorSchemeController from "./color_scheme_controller"
application.register("color-scheme", ColorSchemeController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FormController from "./form_controller"
application.register("form", FormController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import ToggleClassController from "./toggle_class_controller"
application.register("toggle-class", ToggleClassController)
